apiVersion : apps/v1
kind: Deployment
metadata:
  name: "kodeypetest-d779"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "kodeypetest-d779"
  template:
    metadata:
      labels:
        app: "kodeypetest-d779"
    spec:
      containers:
        - name: "kodeypetest-d779"
          image: "06cd9c503afa4455b32b81fb0da4d8ff.azurecr.io/kodeypetest"
          ports:
          - containerPort: 80