apiVersion : apps/v1
kind: Deployment
metadata:
  name: "allhandsaks-8935"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "allhandsaks-8935"
  template:
    metadata:
      labels:
        app: "allhandsaks-8935"
    spec:
      containers:
        - name: "allhandsaks-8935"
          image: "kapasrijkubacr.azurecr.io/allhandsaks8935"
          ports:
          - containerPort: 80