apiVersion: v1
kind: Service
metadata:
    name: "test101-8fbb"
    labels:
        app: "test101-8fbb"
spec:
    type: LoadBalancer
    ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    selector:
        app: "test101-8fbb"