apiVersion: v1
kind: Service
metadata:
    name: "jysinaks1-deff"
    labels:
        app: "jysinaks1-deff"
spec:
    type: LoadBalancer
    ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    selector:
        app: "jysinaks1-deff"