apiVersion: v1
kind: Service
metadata:
    name: "jysinakscluster-9d0d"
    labels:
        app: "jysinakscluster-9d0d"
spec:
    type: LoadBalancer
    ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    selector:
        app: "jysinakscluster-9d0d"